### ISSUE TITLE
raise NotImplementedError for unsupported steering vectors in BeamformerTime classes

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#103]
Currently only one steering vector formulation is implemented in the time beamformers. This is misleading because different formulations can be set using the steering vector class. However, these are not used by BeamformerTime classes.

It would therefore be better to allow only one Steering vector formulation and to throw a NotImplementedError for all others.

**Comment by esarradj** [comment]
see also #58

 *By Gert Herold on 2020-04-09T15:06:49 (imported from GitLab)*

**Comment by adku1173** [comment]
since #318 , time beamformers can use different steering vector formulations (no need for not implemented errors).
