### ISSUE TITLE
PyQt5 incorrect API

### ISSUE THREAD

**Issue by adrien59cadri** [acoular/acoular#11]
Hello,

I've created a specific anaconda environment for acoular,
In this environment PyQt5 is installed as PyQt, on top of python 2.7.13
![image](https://cloud.githubusercontent.com/assets/536398/23168629/cbc77334-f816-11e6-8d95-05ffea99db85.png)

Although, when i launch `python acoular_demo.py` i get this error
![image](https://cloud.githubusercontent.com/assets/536398/23168702/1086db22-f817-11e6-8160-a12969f6a5b5.png)

I've found that pyface 4.4.0 is installed, and even the latest pyface version does not support qt5,
So i guess i should not use pyqt5.

EDIT: FYI I also tried to recreate a clean anaconda 2.7 environment and only install `conda install -c acoular acoular` Then run acoular_demo.py and i get exactly the same error.

Could anyone advise?

thanks in adavance.

PS, I'm on windows 10,

**Comment by gherold** [comment]
Okay, that one's a little ugly. It seems to only appear on Windows and is caused by the traitsui package not supporting qt5. Just installing pyqt=4 doesn't resolve anything.

The fastest workaround here is probably to add the following lines at the very top of all python scripts using acoular (i.e., you'd have to edit the _acoular_demo.py_):
```
import os
os.environ["QT_API"] = "pyqt"
```
I found this solution [here](https://www.scivision.co/mayavi-qt5-create-conda-env-qt4/).

Hope this helps.

**Comment by adrien59cadri** [comment]
Hello, thanks for your answer,

I tried this, I ran into another issue:
![image](https://cloud.githubusercontent.com/assets/536398/23216013/71a6fdf8-f8e2-11e6-8e0d-f523524bcf43.png)

I read here: http://stackoverflow.com/questions/19231944/anaconda-unable-to-import-pylab
That matplotlib backend has to be set to 'pyside' instead of 'pyqt4' sometime,

This relates to an anaconda issue: https://github.com/ContinuumIO/anaconda-issues/issues/8 which is closed now. That suggested QT_QPI should be set to pyside...

**I wonder if enforcing the QT_API=pyqt is confliting with all this**

**Comment by gherold** [comment]
Did you install matplotlib in this environment? While not necessary in general for using acoular, you'll need it for display purposes when running _acoular_demo.py_.

**Comment by adrien59cadri** [comment]
Oh thank you it was just that, i m sorry, i had checked for pyplot, but it s part of matplotlib.

Thanks so much for the help.
It works :)

Now i can dive in Acoular which seems very interesting
