### ISSUE TITLE
Integration with an external Microphone array

### ISSUE THREAD

**Issue by harshmunshi** [acoular/acoular#12]
Hi, Can we integrate Acoular lib with external microphone array? If so how? I see that you have used predefined files in the examples, how to approach the real time processing?

**Comment by esarradj** [comment]
Hi, Acoular includes an undocumented preliminary interface to nidaq, see nidaqimport and ResultExplorer GUI. Acoular is not designed for real time processing though.

**Comment by kylecavs** [comment]
I am interested in characterizing a MEMs microphone array of different geometries. I am looking at example3.py and it shows capability for loading in the array geometry, however how are the calibration factors defined? Ultimately, I am looking for a way to test an array's performance knowing characteristics about the microphone, such as directivity.
