### ISSUE TITLE
Make acoular_demo.py matplotlib independent + call in tests

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#130]
modify acoular_demo.py such that it can also be executed if matplotlib cannot be imported (e.g. print mic geom as array, calculate max or sum of array), add it to tests

**Comment by esarradj** [comment]
This would probably require complicated code in the demo. Maybe just check if matplotlib available and print out a meaningful message. There could also be another matplotlib-less demo.

**Comment by adku1173** [comment]
Related to #233
