### ISSUE TITLE
Behaviour of MicGeom if loaded file not found is incorrect

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#137]
```
if not path.isfile(self.from_file):
            # no file there
            self.mpos_tot = array([], 'd')
            self.num_mics = 0
```
Last line is not possible and causes error, as `num_mics` is read-only property. Line can just be deleted, as the getter function for `num_mics` looks at shape of `mpos_tot`, which would be 0 then.

**Comment by esarradj** [comment]
did you already fix this issue? It is not in the main branch at line 731 anymore

 *By Simon Jekosch on 2021-01-18T10:28:59 (imported from GitLab)*

**Comment by adku1173** [comment]
fixed by !153. Close issue.
