### ISSUE TITLE
Canceling a calculation of an Acoular pipeline including an instance of class TimeCache is problematic

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#141]
If the calculation is interrupted, it happens that the TimeCache has already written data to the cache file. However, the result may not be complete. As a consequence, the pipeline stops too early when the calculation is restarted, since the incomplete data is loaded from the cache. 

One might overthink the TimeCache philosophy. One solution would be to create a new dataset inside the file for each calculated block. If one is missing, it has to be calculated and added. One could also trigger a warning to indicate that the pipeline may have been interrupted before.

**Comment by FrankK20** [comment]
Added a simple example which demonstrates this problem. By manual interruption of the yielding process an incomplete cache file is written, which is later used without any warnings.   [minimal.py](https://git.tu-berlin.de/acoular-dev/acoular/uploads/75ce490ce05a97d491d1fc9e50202d2c/minimal.py)

**Comment by FrankK20** [comment]
created merge request !179 to address this issue

**Comment by esarradj** [comment]
!180 closes this
