### ISSUE TITLE
inplace manipulation of SourceMixer source list does not change digest

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#146]
see minimum example [acoular_sm_bug.py](https://git.tu-berlin.de/acoular-dev/acoular/uploads/a0f9d1f3fe6ec26d4e56feef484cb2a0/acoular_sm_bug.py).

The reason is the trait notification handler (https://docs.enthought.com/traits/traits_user_manual/listening.html).
Instead of `on_trait_change("sources")` it has to be `on_trait_change("sources[]")` to trigger a notification on list item changes.

**Comment by esarradj** [comment]
Check if the behaviour is also buggy when only elements of CArrays are changed.

 *By Gert Herold on 2021-01-21T08:31:45 (imported from GitLab)*

**Comment by adku1173** [comment]
Unfortunately yes.

Consider this simple example:

```
from os import path
from acoular import __file__ as bpath, MicGeom

micgeofile = path.join(path.split(bpath)[0],'xml','array_64.xml')

mg = MicGeom(from_file=micgeofile)

d1 = mg.digest

mg.mpos_tot[0,:] = 0.0

d2 = mg.digest

assert d1 != d2
```

Assertion gets raised in my case.

**Comment by adku1173** [comment]
Obviously there is no chance to listen to item changes of CArrays with the traits.api. All semantics related to item changes are only mentioned in the context of lists, dicts and sets: https://docs.enthought.com/traits/traits_user_manual/notification.html#observe-mini-language

**Comment by adku1173** [comment]
There might be one simple solution for this problem: One could delete the `@cached_property` decorator of the `_get_digest` function (only for classes where the digest depends on an Array/CArray trait).

@esarradj or @gherold Any problems with this?
Calculating the digest may take some time for very large arrays. In context of MicGeom object, this is rather small: 

```
micgeofile = path.join(path.split(bpath)[0],'xml','array_64.xml')

mg = MicGeom(from_file=micgeofile)

print(timeit(lambda: mg.digest,number=500)/500)
``` 

with caching digest: 4.6623000525869427e-07 

without caching digest: 0.0015244382959790528

**Comment by gherold** [comment]
I would suggest to _not_ delete the cached property in general, as this would also mean that upstream digests are calculated over and over again. However, for array/list traits where we suspect that their content might change (and which are not too large), we could introduce a non-cached "specific digest" which is then fed into in the overall digest.

**Comment by adku1173** [comment]
The following refers only to List traits (not to CArrays):

If a notification is triggered on item change depends on the version of the traits package.
For traits >= 6. notifications will also be triggered on list item changes. For traits < 6. it is necessary to explicitly specify that listening is performed on changes of items: e.g. via `on_trait_change("list_trait[]")` 

Note that the usage of `on_trait_change("list_trait[]")` is not included in the traits documentation anymore for traits > 6 (see: https://docs.enthought.com/traits/traits_user_manual/notification.html#observe-mini-language). However, using it does not cause any errors.

There are two possibilities:
1. change the meta.yaml files to traits >= 6.
2. change all depends_on and on_trait_change method arguements with lists from "list_trait" to "list_trait[]" to keep track with older traits versions.

I would prefer number 1. 
@esarradj @gherold any thoughts on that?

**Comment by adku1173** [comment]
A "specific digest" still does not work for array item changes, since no notification is triggered. The main digest will get the result from cache and the digest will not change. 

I think there is no solution for arrays, except from removing the cached_property decorator or telling the user to always replace arrays when changing their values.

**Comment by adku1173** [comment]
This is not true!

Of course the specific digest was not cached. However, when an item of an array is changed, there is no notification triggered (no matter if cached or not). In fact there is no reason for the main digest to release the cached value.

See here:

```
from os import path
from acoular import __file__ as bpath, MicGeom
from traits.api import HasPrivateTraits, Property, CArray, cached_property, Int
from numpy import array
from acoular.internal import digest



class Test(HasPrivateTraits):
    
    array = CArray()
    
    var = Int(1)
    
    specific_digest = Property( depends_on = ['array'])

    digest = Property( depends_on = ['var','specific_digest'])

    def _get_specific_digest(self):
        return digest(self, 'specific_digest')

    @cached_property
    def _get_digest( self ):
        return digest(self)


t = Test(array=array([1,2]))

d1 = t.digest 
t.array = array([2]) # will change digest
d2 = t.digest

assert d1 != d2

d1 = t.digest 
t.array[0] = 10  # will not change digest
d2 = t.digest

assert d1 != d2 # will get raised

```




Not caching the main digest would change something, because it is specifically queried in all functions related to cache files. A recalculation would always give the correct digest and would prevent to falsely read data from cache.

**Comment by adku1173** [comment]
Proposal: Specific digest should be the cached one and the main digest will not be cached.

This works for me:

```
from os import path
from traits.api import HasPrivateTraits, Property, CArray, cached_property, Int
from numpy import array
from acoular.internal import digest



class Test(HasPrivateTraits):
    
    array = CArray()
    
    var = Int(1)
    
    specific_digest = Property( depends_on = ['var'])

    digest = Property( depends_on = ['array','specific_digest'])

    @cached_property
    def _get_specific_digest(self):
        return digest(self, 'specific_digest')

    def _get_digest( self ):
        return digest(self)


t = Test(array=array([1,2]))

d1 = t.digest 
t.array = array([2]) # will change digest
d2 = t.digest

assert d1 != d2

d1 = t.digest 
t.array[0] = 10  # will change digest
d2 = t.digest

assert d1 != d2 # will not get raised
```

**Comment by gherold** [comment]
i.e. the specific digest gets everything except the arrays/lists?
This looks good. For implementing, rename specific digest. Maybe something like "cacheable_digest" to make clear what it is for...

**Comment by esarradj** [comment]
Not sure if understand correctly. But the problem is that on_trait_change cannot react to changes of Array elements?

A straightforward solution would be to not have any Array-dependent observers and to use (shadow) list trait based properties instead. These would return asarray(<list>) and could even be cached !

**Comment by adku1173** [comment]
Yes, that is correct. 

If I understand correctly, not having any array dependent observers would also require to replace all CArray or Array traits by List traits. Wouldn't that be too cumbersome?
