### ISSUE TITLE
Add FiltWNoiseGenerator

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#149]
add new signal class that can create non-white source spectra based on arma model

**Comment by esarradj** [comment]
The SignalGenerator philosophy somewhat breaks the Acoular pipeline philosophy as it yields a **finite** length signal. Using a FIR filter means that there is a delay and initial zeros unless this is considered in the code.

**Comment by adku1173** [comment]
https://numpy.org/doc/stable/reference/random/generator.html

Numpy suggests to use the newer `default_rng` (PCG64) instead of the old `RandomState` (Mersenne Twister) random generator. When using the recommended random generator in the new `FiltWNoiseGenerator`, the initial signals of `WNoiseGenerator` and `FiltWNoiseGenerator` would not be equal. Has someone concerns about using default_rng or should we stick to the old `RandomState` for consistency reasons?

**Comment by gherold** [comment]
For new classes that are not present in old scripts, default behaviour should be to use non-deprecated functions.

For making FiltWNoiseGenerator compatible with old WNoiseGenerator

Suggestion 1:
 * set `seed` trait in `FiltWNG` to None by default
 * use new `rng_seed` (or other name) trait as default, which can be a number or even a random generator instance
 * if user decides to set old `seed` trait, use old `RandomState` for number generation, otherwise use new tools

Suggestion 2:
 * add new `rng_seed` (or other name) trait (defaults to None) to `WNoiseGenerator` that can be set by user and then supersedes the `seed` trait


Either of the suggestions or both could be implemented and not disrupt anything while keeping up-to-date.

**Comment by esarradj** [comment]
It looks like RandomState is **not** deprecated. See https://numpy.org/neps/nep-0019-rng-policy.html , especially the last paragraph:

... All current usages of RandomState will continue to work in perpetuity, though some may be discouraged through documentation. Unit tests can continue to use the full complement of RandomState methods. Mixed RandomState/Generator code can safely share the common BitGenerator state. Unmodified RandomState code can make use of the new features of alternative BitGenerator-like settable streams.

This would enable to keep RandomState and use whatever seems best for new features.

**Comment by adku1173** [comment]
Also from the article:
The same version of numpy built on different platforms, or just in a different way could cause changes in the stream, with varying degrees of rarity. The biggest is that the .multivariate_normal() method relies on numpy.linalg functions. Even on the same platform, if one links numpy with a different LAPACK, .multivariate_normal() may well return completely different results. More rarely, building on a different OS or CPU can cause differences in the stream. We use C long integers internally for integer distribution (it seemed like a good idea at the time), and those can vary in size depending on the platform. Distribution methods can overflow their internal C longs at different breakpoints depending on the platform and cause all of the random variate draws that follow to be different. [...] The standard practice now for bit-for-bit reproducible research is to pin all of the versions of code of your software stack, possibly down to the OS itself.

**Comment by adku1173** [comment]
Absolute reproducibility can therefore only be guaranteed with the use of containers and fixed package versions anyway.

**Comment by esarradj** [comment]
It is saying: RandomState will be removed from randomgen, because it will stay in Numpy.

**Comment by esarradj** [comment]
mentioned in commit a68e7177dad940b39a242e0ff1d1969f1c4ad250
