### ISSUE TITLE
Increase test coverage for features that are already tested

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#157]
Using coverage, it becomes clear that the present test only cover about 50% of the code lines. This is partly due to some classes and function are not part of test at all, but also due to some parts of the code never being executed.

The latter happens for `if then else` statements where only one branch is tested. The other branch is only executed for different parameter settings than used in the test, e.g. for the other setting of `r_diag`.

**Comment by artpelling** [comment]
#232  adds a basic coverage report to the Tests CI Workflow. This could give some hints as to where the greatest potential for improvement lies.

**Comment by esarradj** [comment]
In the #232 CI workflow coverage is reported for all Python versions which takes around 10m. Is it really necessary to include all Python versions? I would not expect coverage to depend on the Python version.

**Comment by artpelling** [comment]
> In the #232 CI workflow coverage is reported for all Python versions which takes around 10m. Is it really necessary to include all Python versions? I would not expect coverage to depend on the Python version.

That was not intended. Hopefully now fixed by #241.
