### ISSUE TITLE
Error when running acoular_demo.py

### ISSUE THREAD

**Issue by mhcn** [acoular/acoular#16]
acoular is installed successfully through conda.
However,when I try to run the demo,it shows ,

Traceback (most recent call last):
  File "D:\ProgramFiles\anaconda2\Scripts\acoular_demo-script.py", line 27, in <module>
    from acoular import __file__ as bpath, MicGeom, WNoiseGenerator, PointSource,

  File "D:\ProgramFiles\anaconda2\lib\site-packages\acoular\__init__.py", line 80, in <module>
    from .spectra import PowerSpectra, EigSpectra, synthetic
  File "D:\ProgramFiles\anaconda2\lib\site-packages\acoular\spectra.py", line 27, in <module>
    from .fastFuncs import calcCSM
  File "D:\ProgramFiles\anaconda2\lib\site-packages\acoular\fastFuncs.py", line 196, in <module>
    '(m,m),(),(m),(),()->()', nopython=True, target=parallelOption, cache=cachedOption)
  File "D:\ProgramFiles\anaconda2\lib\site-packages\numba\npyufunc\decorators.py", line 165, in wrap
    guvec.add(fty)
  File "D:\ProgramFiles\anaconda2\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 170, in add
    self.nb_func, targetoptions, sig)
  File "D:\ProgramFiles\anaconda2\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 92, in _compile_element_wise_function
    cres = nb_func.compile(sig, **targetoptions)
  File "D:\ProgramFiles\anaconda2\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 63, in compile
    self.targetdescr.options.parse_as_flags(flags, topt)
  File "D:\ProgramFiles\anaconda2\lib\site-packages\numba\targets\options.py", line 26, in parse_as_flags
    opt.from_dict(options)
  File "D:\ProgramFiles\anaconda2\lib\site-packages\numba\targets\options.py", line 19, in from_dict
    raise KeyError(fmt % k)
**KeyError: "Does not support option: 'cache'"**

**Comment by gherold** [comment]
Could you provide the output of 
`conda list`
when run in the Terminal/Anaconda prompt?

**Comment by mhcn** [comment]
The output of `conda list` is 
`# packages in environment at D:\ProgramFiles\anaconda2:
#
acoular                   17.11            py27ha02c866_0    acoular
alabaster                 0.7.7                    py27_0    defaults
anaconda                  4.0.0               np110py27_0    defaults
anaconda-client           1.4.0                    py27_0    defaults
anaconda-navigator        1.1.0                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astropy                   1.1.2               np110py27_0    defaults
babel                     2.2.0                    py27_0    defaults
backports_abc             0.4                      py27_0    defaults
beautifulsoup4            4.4.1                    py27_0    defaults
bitarray                  0.8.1                    py27_1    defaults
blaze                     0.9.1                    py27_0    defaults
bokeh                     0.11.1                   py27_0    defaults
boto                      2.39.0                   py27_0    defaults
bottleneck                1.0.0               np110py27_0    defaults
bzip2                     1.0.6                     vc9_2  [vc9]  defaults
cdecimal                  2.3                      py27_1    defaults
cffi                      1.5.2                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
cloudpickle               0.1.1                    py27_0    defaults
clyent                    1.2.1                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
comtypes                  1.1.2                    py27_0    defaults
conda                     4.3.30           py27he817781_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-build               1.20.0                   py27_0    defaults
conda-env                 2.6.0                h36134e3_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
conda-manager             0.3.1                    py27_0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0            py27h2fa79a8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
console_shortcut          0.1.1                    py27_1    defaults
cryptography              1.4                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
curl                      7.45.0                    vc9_1  [vc9]  defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.23.4                   py27_0    defaults
cytoolz                   0.7.5                    py27_0    defaults
dask                      0.8.1                    py27_0    defaults
datashape                 0.5.1                    py27_0    defaults
decorator                 4.0.9                    py27_0    defaults
dill                      0.2.4                    py27_0    defaults
docutils                  0.12                     py27_1    defaults
enum34                    1.1.2                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_0    defaults
flask                     0.10.1                   py27_1    defaults
flask-cors                2.1.2                    py27_0    defaults
freetype                  2.5.5                     vc9_0  [vc9]  defaults
funcsigs                  0.4                      py27_0    defaults
futures                   3.0.3                    py27_0    defaults
gevent                    1.1.0                    py27_0    defaults
greenlet                  0.4.9                    py27_0    defaults
grin                      1.2.1                    py27_2    defaults
h5py                      2.5.0               np110py27_4    defaults
hdf5                      1.8.15.1                  vc9_4  [vc9]  defaults
heapdict                  1.0.0                    py27_0    defaults
idna                      2.0                      py27_0    defaults
ipaddress                 1.0.14                   py27_0    defaults
ipykernel                 4.3.1                    py27_0    defaults
ipython                   4.1.2                    py27_1    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                4.1.1                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jdcal                     1.2                      py27_0    defaults
jedi                      0.9.0                    py27_0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
jsonschema                2.4.0                    py27_0    defaults
jupyter                   1.0.0                    py27_2    defaults
jupyter_client            4.2.2                    py27_0    defaults
jupyter_console           4.1.1                    py27_0    defaults
jupyter_core              4.1.0                    py27_0    defaults
libpng                    1.6.17                    vc9_1  [vc9]  defaults
libsodium                 1.0.3                         0    defaults
libtiff                   4.0.6                     vc9_1  [vc9]  defaults
llvmlite                  0.9.0                    py27_0    defaults
locket                    0.2.0                    py27_0    defaults
lxml                      3.6.0                    py27_0    defaults
markupsafe                0.23                     py27_1    defaults
matplotlib                1.5.1               np110py27_0    defaults
menuinst                  1.3.2                    py27_0    defaults
mistune                   0.7.2                    py27_0    defaults
mkl                       11.3.1                        0    defaults
mkl-service               1.1.2                    py27_0    defaults
mpmath                    0.19                     py27_0    defaults
multipledispatch          0.4.8                    py27_0    defaults
nbconvert                 4.1.0                    py27_0    defaults
nbformat                  4.0.1                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2                      py27_0    defaults
nose                      1.3.7                    py27_0    defaults
notebook                  4.1.0                    py27_2    defaults
numba                     0.24.0              np110py27_0    defaults
numexpr                   2.5                 np110py27_0    defaults
numpy                     1.10.4                   py27_0    defaults
odo                       0.4.2                    py27_0    defaults
openpyxl                  2.3.2                    py27_0    defaults
openssl                   1.0.2g                    vc9_0  [vc9]  defaults
pandas                    0.18.0              np110py27_0    defaults
partd                     0.3.2                    py27_1    defaults
path.py                   8.1.2                    py27_1    defaults
patsy                     0.4.0               np110py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pickleshare               0.5                      py27_0    defaults
pillow                    3.1.1                    py27_0    defaults
pip                       8.1.1                    py27_1    defaults
ply                       3.8                      py27_0    defaults
psutil                    4.1.0                    py27_0    defaults
py                        1.4.31                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycosat                   0.6.1                    py27_0    defaults
pycparser                 2.14                     py27_0    defaults
pycrypto                  2.6.1                    py27_3    defaults
pyface                    5.1.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyflakes                  1.1.0                    py27_0    defaults
pygments                  2.1.1                    py27_0    defaults
pyopenssl                 16.2.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
pyparsing                 2.0.3                    py27_0    defaults
pyqt                      4.11.4                   py27_5    defaults
pyreadline                2.1                      py27_0    defaults
pytables                  3.2.2               np110py27_2    defaults
pytest                    2.8.5                    py27_0    defaults
python                    2.7.13                        1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
python-dateutil           2.5.1                    py27_0    defaults
pytz                      2016.2                   py27_0    defaults
pywin32                   220                      py27_1    defaults
pyyaml                    3.11                     py27_3    defaults
pyzmq                     15.2.0                   py27_0    defaults
qt                        4.8.7                     vc9_7  [vc9]  defaults
qtawesome                 0.3.2                    py27_0    defaults
qtconsole                 4.2.0                    py27_1    defaults
qtpy                      1.0                      py27_0    defaults
requests                  2.12.4                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
scikit-image              0.12.3              np110py27_0    defaults
scikit-learn              0.17.1              np110py27_0    defaults
scipy                     0.17.0              np110py27_0    defaults
setuptools                20.3                     py27_0    defaults
simplegeneric             0.8.1                    py27_0    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.16.9                   py27_2    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.1                    py27_0    defaults
sphinx                    1.3.5                    py27_0    defaults
sphinx_rtd_theme          0.1.9                    py27_0    defaults
spyder                    2.3.8                    py27_1    defaults
sqlalchemy                1.0.12                   py27_0    defaults
ssl_match_hostname        3.4.0.2                  py27_0    defaults
statsmodels               0.6.1               np110py27_0    defaults
sympy                     1.0                      py27_0    defaults
tk                        8.5.18                    vc9_0  [vc9]  defaults
toolz                     0.7.4                    py27_0    defaults
tornado                   4.3                      py27_0    defaults
traitlets                 4.2.1                    py27_0    defaults
traits                    4.6.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
traitsui                  5.1.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
unicodecsv                0.14.1                   py27_0    defaults
vc                        9                    h7299396_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
vs2008_runtime            9.00.30729.1         hfaea7d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
vs2010_runtime            10.00.40219.1                 0    defaults
werkzeug                  0.11.4                   py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
xlrd                      0.9.4                    py27_0    defaults
xlsxwriter                0.8.4                    py27_0    defaults
xlwings                   0.7.0                    py27_0    defaults
xlwt                      1.0.0                    py27_0    defaults
zlib                      1.2.8                     vc9_2  [vc9]  defaults
`
I tested it on Ubuntu16.04 and Windows7,they all said `KeyError: "Does not support option: 'cache'"`

**Comment by 1oly** [comment]
Maybe related to this issue when parallel and cache = True ? https://github.com/numba/numba/issues/2441

You could try to set cachedOption=False and see what happens...

**Comment by adku1173** [comment]
This Error is caused by a to low numba version.
Please install at least numba version 0.30.0
According to #PR2190 in Acoular Release Notes: Caching for ufunc is first introduced in this Version -> http://numba.pydata.org/numba-doc/0.30.0/release-notes.html
This should solve your problem.

**Comment by mhcn** [comment]
It works! Thank you!
