### ISSUE TITLE
BeamformerClean destroys BeamformerBase result

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#160]
`BeamformerClean.calc` manipulates on the map of its `self.beamformer` object (`BeamformerBase`). If this object is used later, totally wrong results are read, but only if it was __not__ cached.

The problem is easy to solve, but it has had an impact already on the tests. The reference values for the Damas Beamformers were calculated from the dirty clean maps instead of the beamformer result. These values have to be adapted.

**Comment by adku1173** [comment]
mentioned in commit 347318d2eab5cf54144914f9400ec1febeda8cb8
