### ISSUE TITLE
_delayandsum5 TypeError

### ISSUE THREAD

**Issue by FrankK20** [acoular/acoular#169]
Using BeamformerCleantTraj results in a type error: `TypeError: No matching definition for argument type(s) array(float64, 2d, C), array(int32, 3d, C), array(float32, 3d, C), array(float32, 3d, C), array(float32, 2d, C), array(float32, 2d, C)` from _delayandsum5. There seems to be a missing definition.

**Comment by FrankK20** [comment]
The following minimal example shows this error.[minimal.py](https://git.tu-berlin.de/acoular-dev/acoular/uploads/1a2ec812b7dfa009b3cb8983e204720e/minimal.py)

**Comment by esarradj** [comment]
mentioned in commit 20dd1285076349ab79bb0e3b9aa1505557dbb1a2

**Comment by adku1173** [comment]
mentioned in commit 1d2316a8d88afd5a78a885705d56419663ccad7c
