### ISSUE TITLE
Missing samples in Cleant interpolation

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#170]
When removing the max contribution from microphone signals during the Cleant iteration, some samples could go missing because the results are just taken as integer parts of the suppports `t_ind = t_float.astype(int64)`. The step in `t_float` may be larger than 1.0

**Comment by esarradj** [comment]
mentioned in commit edd7fe67e2592243bbc653998dc26a41c06b9398

**Comment by adku1173** [comment]
mentioned in commit 1d2316a8d88afd5a78a885705d56419663ccad7c
