### ISSUE TITLE
Gridless / adaptive grid beamformers

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#174]
Some methods work without a predefined grid. Instead the (likely or possible) position of sources is given as a result of the method together with the strength of the sources. Our standard implementation cannot handle this situation because:
* the `BeamformerBase.result` gives only the result mapped to (predefined) grid
* the grid needs to be defined before computation

Possible solutions:
1. work without grid class and change the beamformer result to a list or array of tuples with position and strength (x,y,z,p)
    * ++ only a new beamformer class needs to be implemented
    * -- postprocessing routines for plotting etc. cannot be reused, the result is not compatible
    * -- sector integration and sector handling will not work with what is implemented, special handling is required
2. implement a special grid class that uses the same interface as `Grid`, but works on grid locations that are found during computation; implement a new base class for gridless beamformers that is capable of interacting with the special grid class
    * -- new grid and beamformer classes needed
    * -- caching needs to handle grid locations, complicated implementation
    * ++ sector integration will work without change
    * ++ normal postprocessing routines will work
3. map the result to a fixed grid as defined with one of the existing grid classes
    * ++ only a new beamformer class needs to be implemented
    * ++ caching will work out of the box
    * ++ sector integration will work without change
    * ++ normal postprocessing routines will work
    * -- reduced spatial resolution of the result

**Comment by gherold** [comment]
Solution 2. 

Mapping of the result of one grid to another grid could be handled separately in an independent class.

It may be a good idea to add grid information to caching anyway (at least optionally).

**Comment by esarradj** [comment]
Refined idea for solution 2:
* Adaptive Grid Beamformer class 
    * bases on both `Grid` and `BeamformerBase` (no need for extra Grid class)
    * uses a `SteeringVector` without (!) `Grid` (or it is neglected)
    * `gpos` trait is cached 
    * slight modifications to account for the absence of `steer.grid`
* Results for all frequencies will live in on the same grid, but each frequency will use different points. This leads to extremely sparse results for each grid. Because we use compressed hdf5 cache objects, this is no storage problem (at least I hope so). The grid will have a size of number of frequencies X number of sources per frequency.

**Comment by gherold** [comment]
gpos trait: does this mean that we get a grid with nsources x nfreqs entries or is nsources not pre-defined? There could be problems regarding the evaluated frequency range (ind_low, ind_high), in that the grid will depend on this and there would be re-calculations of cached data if range borders are changed -- or maybe not if pre-allocated with fixed nsources. An alternative would be to cache "grid per frequency" & use this class-internally but translate it to normal grid in the interface.

**Comment by esarradj** [comment]
No, it is the same grid with say 65536 positions for all frequencies, but only 32 positions are nonzero for each of 2048 frequencies. Generally no position is nonzero except for the result of one frequency. While this is not necessarily the case with present Beamformers/Grids it is also no problem for the existing routines.

One possible problem could be the huge size of the result (65536 x 2048) in the example. This is no problem if the result is cached because the result will never fully be in memory and on disk it is compressed (zeros take no space !). If the result is not cached, it lives in memory. But this is a special case _and_ we could still handle it if we use sparse arrays (I would not implement this now).
