### ISSUE TITLE
New Beamformer-class function "condense" for replacing/enhancing synthetic+integrate?

### ISSUE THREAD

**Issue by gherold** [acoular/acoular#175]
Suggestion to add a new function in the BeamformerBase function that comprises the functionality of both ".synthetic" and ".integrate". Purpose is to compress the result data and extract the actually interesting info (e.g. third-octave bands in defined sectors).

Most of the arguments passed to the function should be optional, so that it can be used more or less in the same way as .synthetic or .integrate alone. This would also make using the corresponding standalone functions after first applying .synthetic or .integrate unnecessary.

Important differences to the old functions are
- no reshaping to grid anymore (should be done somewhere else)
- ability to handle multiple requested frequency bands and sectors (but also still single ones)

The implementation of this could include a deprecation warning for .synthetic and .integrate

Any thoughts or naming ideas? (condense/compress/extract ... )

**Comment by esarradj** [comment]
We could implement a private helper synthetic + integrate = condense function.
In addition, we alter the interface of the existing functions

`
def synthetic( self, f, num=0, sector=None):
`

`
def integrate( self, sector, f=0, num=0):
`

**Comment by gherold** [comment]
This could work as well.
