### ISSUE TITLE
documentation synthetic

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#177]
In GitLab by @erik.w.schneehagen on Sep 8, 2022, 17:52

In the documentation of the synthetic-function it says that the input is "the spectral data (sound pressures in Pa)" but actually it is "squared sound pressure values in Pa**2" which would be in accordance to the documentation of Beamformer.result().

**Comment by sjekosch** [comment]
mentioned in commit 1b7bcf9a4004b4502113aeea639ea6ba57ad58ce
