### ISSUE TITLE
gitlab-ci.yml uses conda and pip which results in pipeline failures

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#179]
Pipelines fail for version acoular 22.3 due to version conflicts of numba (installed by pip) and setuptools (installed by conda). (Setuptools should be smaller < 60., but pip cannot change the version that has been defined by conda)

**Comment by esarradj** [comment]
It seems like this conflict arises from nasty interaction between conda and pip. The CI is based entirely on pip except for the basic Python install. Maybe it would be better to rewrite gitlab-ci.yml to use pip/virtualenv instead of conda. Also, the docker image used seems to be a bit outdated?

**Comment by adku1173** [comment]
That is exactly what my last comment was saying https://git.tu-berlin.de/acoular-dev/acoular/-/issues/179#note_269675. The gitlab-ci.yml makes use of conda and pip at the same time, which is the reason for the conflict. Sorry, the issue title might not imply this.

**Comment by esarradj** [comment]
resolved in !209
