### ISSUE TITLE
How to import .mat file format into acoular?The question of fileimport.py codes

### ISSUE THREAD

**Issue by Qinstudy** [acoular/acoular#18]
Hello developer! I use the .mat data format to do the sound source localization. At present, I'm doing the conversion of the .mat data format to the .hdf5 file format. I check out the class bk_mat_import class that you wrote in fileimport.py. I tried to call this class , but I failed! Excuse me, can you give a example of importing mat files? If you can, thank you very much!

**Comment by esarradj** [comment]
see https://gist.github.com/esarradj/5ada1e1d980bf1c39288757894553991 for an example

**Comment by Qinstudy** [comment]
Thank  you very much !

**Comment by Qinstudy** [comment]
Thank,@esarradj
