### ISSUE TITLE
Refactor SteeringVector class and fastFuncs.py

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#186]
In the different beamformer functions (e.g. `_freqBeamformer_Formulation1AkaClassic_FullCSM`) in `fastFuncs.py`, the steering vector calculation is included. I suggest to handle the steering vector calculation in the `SteeringVector` class (by keeping fast core functions in the `fastFuncs` module). At the same time this would make a whole lot of duplicate code obsolete.

Moreover, the current behaviour unnecessarily limits the performance of `BeamformerOrth`. For each eigenvalue-eigenvector pair, the SteeringVector is calculated again.

**Comment by esarradj** [comment]
Resolved by !234
