### ISSUE TITLE
Unstable Filters

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#191]
Several classes derived from `tprocess.Filter` exhibit unstable behavior in the filter process due to numerical errors. This happens most notably for low filter frequencies. E.g. a third octave filter breaks down for 20 Hz center frequency when the sample frequency is 51.2 kHz and delivers a numerical overflow error. 

Moreover, the filter output depends on the numerical libraries used by numpy/scipy. E.g. different output is produced be 'tprocess.FiltFiltOctave' for a 100 Hz third octave filter, when conda or pip installed scipy is used.

A possible remedy would be to replace simple IIR-filters by more stable SOS filters.

**Comment by sjekosch** [comment]
mentioned in commit 8306fc2656ff852d59ca186a411b52d118760885
