### ISSUE TITLE
Pymor links in the readme

### ISSUE THREAD

**Issue by sjekosch** [acoular/acoular#192]
The shields.io links in the readme.md still go to pymor:

[![PyPI](https://img.shields.io/pypi/pyversions/acoular.svg)](https://pypi.python.org/pypi/pymor)
[![PyPI](https://img.shields.io/pypi/v/acoular.svg)](https://pypi.python.org/pypi/pymor)

should got to acoular instead: https://pypi.org/project/acoular/

**Comment by sjekosch** [comment]
created branch [`192-pymor-links-in-the-readme`](/acoular-dev/acoular/-/compare/master...192-pymor-links-in-the-readme) to address this issue

**Comment by esarradj** [comment]
mentioned in commit e3c094d9248de971eea5d58461cfb5cc7255e667
