### ISSUE TITLE
ImportGrid relies on nonexistent attributes

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#193]
`ImportGrid` does not work as expected.

1. `index(x,y)` method:
* (1) It is not possible to work in 3D (only accepts x and y as inputs)
* (2) Makes use of self.x_min, self._y_min, etc., which is not an attribute of the class since it is derived from Grid
* (3) Since `index` cannot be used without errors, `indices` will also be broken
2. Documentation:
* in `import_gpos`: Import the microphone positions from .xml file.
* Missing sphinx descriptions at subgrids attribute
If it is not expected to work in 3D, it should be at least reflect in the class name that it is only for 2D grid imports.

**Comment by sjekosch** [comment]
created branch [`193-importgrid-relies-on-nonexistent-attributes`](/acoular-dev/acoular/-/compare/master...193-importgrid-relies-on-nonexistent-attributes) to address this issue

**Comment by esarradj** [comment]
mentioned in commit 73260537af6b0b58cfecb323c09a102b09f6bec4
