### ISSUE TITLE
BeamformerCMF with "NNLS" method throws error

### ISSUE THREAD

**Issue by gherold** [acoular/acoular#195]
When using BeamformerCMF with `method` trait set to `'NNLS'`, the program exits with error:

`TypeError: LinearRegression.__init__() got an unexpected keyword argument 'normalize'`

This is due to line 1902 in fbeamform.py `model = LinearRegression(normalize=False, positive=True)`, scikit-learn's function LinearRegression not accepting the `normalize` parameter.

**Comment by adku1173** [comment]
mentioned in commit cb135f7a413dadef5e939308da393a6eb7c9287d
