### ISSUE TITLE
BeamformerOrth assigns strongest source always at grid index 0

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#198]
`BeamformerOrth` assigns strongest source at grid index 0 when instead of `eva_list` the trait `n` is given. This leads for `n=3` to 'eva_list = [-3,-2,-1]`. For -1, an empty eve array is sent to the beamformer, returning a blank result.

**Comment by esarradj** [comment]
created branch [`198-beamformerorth-assigns-strongest-source-always-at-grid-index-0`](/acoular-dev/acoular/-/compare/master...198-beamformerorth-assigns-strongest-source-always-at-grid-index-0) to address this issue

**Comment by sjekosch** [comment]
mentioned in commit 08c3cf589d9243ed19e736d0dff332c2517da32c
