### ISSUE TITLE
Initial guess in SODIX

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#200]
In GitLab by @sebastian.oertwig on Jan 11, 2024, 19:09

The initial guess within the optimization problem in SODIX is given for the source directivities D which are proportional to the square root of the unit of the CSM, i.e. the unit of D is Pa when the unit of the CSM is Pa^2.

In Acoular, the derived source directivities are taken to the power of two (see https://git.tu-berlin.de/acoular-dev/acoular/-/blob/master/acoular/fbeamform.py?ref_type=heads#L2248) in order to compute source powers. These source powers are then provided as the initial guess for the source directivities D at the new frequency (see https://git.tu-berlin.de/acoular-dev/acoular/-/blob/master/acoular/fbeamform.py?ref_type=heads#L2233). I think this problem can add up for larger numbers of frequency bins.

In this last line, there should be at least a square root involved, i.e. D0 = sqrt(ac[(i-1)]).
I also looked into the initial guess in my PhD thesis and found that it is best when the intial guess reproduces the "energy" measured by the microphone array. Therefore, I scaled the SODIX solution with the energy norms of the modelled CSM of the previous frequency and the measured CSM of the current frequency.

**Comment by esarradj** [comment]
!251 implements this
