### ISSUE TITLE
Zenodo author data

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#206]
The Acoular entry on Zenodo shows partially wrong data, especially regarding the authors. This can be fixed using a (badly documented) `zenodo.json` file, see [here](https://stackoverflow.com/questions/57427477/how-to-template-zenodo-auto-release-archive).

**Comment by adku1173** [comment]
Should we use "Department of Engineering Acoustics, TU Berlin" or "Fachgebiet Technische Akustik"?

**Comment by esarradj** [comment]
I don't think we should use an affiliation at all. Eventually, this may change for some contributors and we would need to keep track of this per release. Instead, we can make use of ORCID numbers.

**Comment by esarradj** [comment]
One second thought, there are people without ORCID, so the affiliation gives some extra information to distinguish from other people with the same name. So let's keep the affiliation at the time of last contribution.

**Comment by adku1173** [comment]
Should we cite all the contributors (even for previous releases)? I guess, there are more than the ones in the current .json file in my MR.

**Comment by esarradj** [comment]
I think we can safely ignore people with just one of two minor commits. For me it seems like all others are included:

279 Simon Jekosch s.jekosch@tu-berlin.de 230 Ennes Sarradj sarradj@tu-cottbus.de 195 Gert Herold g.j.h@gmx.net 175 esarradj ennes.sarradj@tu-berlin.de 125 adamkujawski kujawski.ad@gmail.com 95 sjekosch 44668203+sjekosch@users.noreply.github.com 94 Gert Herold gert.herold@tu-berlin.de 48 Adam Kujawski adam.kujawski@tu-berlin.de 37 Tom Jan Gensch tom.j.gensch@campus.tu-berlin.de 31 GH gejohe@web.de 30 Mikolaj Czuchaj mikolaj.czuchaj@tu-berlin.de 28 Adam Kujawski adam.kujawski@campus.tu-berlin.de 26 Tom Gensch tom.j.gensch@campus.tu-berlin.de 25 Ennes Sarradj ennes.sarradj@tu-berlin.de 24 Ennes Sarradj ennes.sarradj@gmx.de 19 adku1173 adam.kujawski@tu-berlin.de 16 sarradj ennes.sarradj@tu-berlin.de 14 herold gert.herold@tu-berlin.de 13 Art Joshua Robert Pelling art.jr.pelling@campus.tu-berlin.de 11 esarradj ennes.sarradj@gmx.de 10 Gert Herold gejohe@web.de 4 simonjekosch s.jekosch@tu-berlin.de 3 Art Pelling a.pelling@tu-berlin.de 3 pelling art.jr.pelling@campus.tu-berlin.de 2 Art Joshua Robert Pelling a.pelling@tu-berlin.de 2 Todd toddrme2178@gmail.com 2 gherold gherold@users.noreply.github.com 1 CarlosAMolina carlosantmolina@gmail.com 1 Kujawski, Adam adam.kujawski@tu-berlin.de 1 Sarradj, Ennes, Prof. Dr ennes.sarradj@tu-berlin.de 1 mikolaj.czuchaj mikolaj.czuchaj@tu-berlin.de 1 sarradj \<sarradj@stanilaw.(none)\>

**Comment by esarradj** [comment]
mentioned in commit 7153d8dcd2bc9550fb874df53c126267946da3c3

**Comment by adku1173** [comment]
With today's release, it becomes apparent that zenodo ignores the zenodo.json file. And it is totally unclear why this happens...

**Comment by esarradj** [comment]
mentioned in commit b8a8c6b13a36e9c4bc6d2351cccd508bbbceed23
