### ISSUE TITLE
issue installing with conda

### ISSUE THREAD

**Issue by 5ke** [acoular/acoular#21]
Hi!

When using `conda install -c acoular acoular` I get 3 subsequent SafetyErrors:

> SafetyError: The package for acoular located at ... appears to be corrupted. The path X has a sha256 mismatch.

with X:
- 'Scripts/CalibHelper-script.py'
- 'Scripts/ResultExplorer-script.py'
- 'Scripts/acoular_demo-script.py'

followed by 4 ClobberErrors

> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
>   path: 'lib/site-packages/jupyter.py'

> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: conda-forge::jupyter_core-4.4.0-py_0, conda-forge::jupyter-1.0.0-py_1
>   path: 'lib/site-packages/__pycache__/jupyter.cpython-36.pyc'

> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: conda-forge::ipykernel-5.1.0-py36h39e3cac_1001, conda-forge::widgetsnbextension-3.4.2-py36_1000
>   path: 'scripts/jupyter-kernel-script.py'

> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: conda-forge::ipykernel-5.1.0-py36h39e3cac_1001, conda-forge::widgetsnbextension-3.4.2-py36_1000
>   path: 'scripts/jupyter-kernel.exe'

I've tried removing the cached package, and also just installing on another system that didn't have acoular from before. This didn't help, so I wonder if something is wrong with the latest Acoular library on conda.

**Comment by gherold** [comment]
This problem seems to appear recently when you try installing Acoular on Windows systems and will be fixed in the next release. Have you checked whether Acoular has not actually been installed nonetheless? (e.g., type "import acoular" in a python console)

**Comment by 5ke** [comment]
Great to hear a fix is on its way!

Yes, I forgot to say, afterwardsthe install works fine, but installing it this way takes forever.
