### ISSUE TITLE
Extensive code line length

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#214]
Some files include very long lines of code (>120 characters), including:
* [fastFuncs.py](acoular/fastFuncs.py)
* [fbeamform.py](acoular/fbeamform.py)
* [nidaqimport.py](acoular/nidaqimport.py)
* [signals.py (line 343)](acoular/signals.py)
* [sources.py (line 521)](acoular/sources.py)
* [spectra.py (line 741)](acoular/spectra.py)
* ... etc.

What code line length shall we consider to be valid?

**Comment by artpelling** [comment]
I think 120 for code and 100 for docstrings is nice. IMO, anything over 120 can definitely be considered too long but sometimes it is nice to be able to have a long line. For the docstrings, 100 is more on the long side but should keep them readable even in a split screen without scrolling.
