### ISSUE TITLE
Unused arguments in some functions and methods

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#226]
There exist some methods and functions with unused arguments (For most of these methods, this was intended).
Here we need to decide if it is really necessary to keep unused arguments (e.g. in fastFuncs.py)

Output: 
```
acoular/environments.py:244:18: ARG002 Unused method argument: `xx`
acoular/environments.py:623:16: ARG001 Unused function argument: `t`
acoular/fastFuncs.py:523:33: ARG001 Unused function argument: `distGridToArrayCenter`
acoular/fastFuncs.py:573:38: ARG001 Unused function argument: `distGridToArrayCenter`
acoular/h5files.py:45:33: ARG002 Unused method argument: `group`
acoular/nidaqimport.py:159:35: ARG002 Unused method argument: `dispatch`
acoular/sdinput.py:65:33: ARG002 Unused method argument: `change`
acoular/sources.py:1254:36: ARG002 Unused method argument: `event`
acoular/tfastfuncs.py:88:18: ARG001 Unused function argument: `r0`
acoular/tfastfuncs.py:129:19: ARG001 Unused function argument: `r0`
acoular/tools.py:210:23: ARG001 Unused function argument: `derivativearccos`
acoular/tprocess.py:465:30: ARG002 Unused method argument: `x0`
acoular/tprocess.py:752:48: ARG002 Unused method argument: `method`
acoular/tprocess.py:752:56: ARG002 Unused method argument: `array_dimension`
acoular/tprocess.py:752:73: ARG002 Unused method argument: `interp_at_zero`
acoular/tprocess.py:899:62: ARG002 Unused method argument: `Q`
acoular/tprocess.py:899:67: ARG002 Unused method argument: `interp_at_zero`
acoular/tprocess.py:1235:36: ARG002 Unused method argument: `event`
```

**Comment by adku1173** [comment]
The `SpatialInterpolator` class includes the public attributes `interp_at_zero` and `Q`. 

https://github.com/acoular/acoular/blob/d06d58c6f8101ff9ff186905e43802cc19f5b058/acoular/tprocess.py#L720-L721

At the same time, the method `_result_core_func` has arguments `interp_at_zero` and `Q`, which are never used inside the function code (only the class attribute is used via `self.interp_at_zero`:

https://github.com/acoular/acoular/blob/d06d58c6f8101ff9ff186905e43802cc19f5b058/acoular/tprocess.py#L913-L1134

I believe we can delete the method arguments. But what confuses me is that when the method is called in the subclasses `SpatialInterpolatorConstantRotation` and `SpatialInterpolatorRotation`, these unused arguments are given with `interp_at_zero = False`.

https://github.com/acoular/acoular/blob/d06d58c6f8101ff9ff186905e43802cc19f5b058/acoular/tprocess.py#L1178

 @gherold, could you tell me what the concept was here? Obviously, `interp_at_zero` can also be `True`, and the arguments can be deleted. Is that correct?

**Comment by adku1173** [comment]
@esarradj Can we safely delete the unused `dispatch` argument? For what was it intended?

https://github.com/acoular/acoular/blob/d06d58c6f8101ff9ff186905e43802cc19f5b058/acoular/nidaqimport.py#L163-L177

**Comment by esarradj** [comment]
`dispatch` is a remainder (i guess) from the Python 2 days when we were using this in the ResultExplorer GUI. However, before putting effort in the `nidaqimport` module at all, we should decide if we keep it. It is seriously outdated and is probably not working anymore anyway.

**Comment by esarradj** [comment]
```
acoular/fastFuncs.py:523:33: ARG001 Unused function argument: `distGridToArrayCenter`
acoular/fastFuncs.py:573:38: ARG001 Unused function argument: `distGridToArrayCenter`
```
This is needed because the functions have to have the exact same arguments as other PSF functions.

**Comment by adku1173** [comment]
related to #233

**Comment by gherold** [comment]
> The `SpatialInterpolator` class includes the public attributes `interp_at_zero` and `Q`.
> 
> https://github.com/acoular/acoular/blob/d06d58c6f8101ff9ff186905e43802cc19f5b058/acoular/tprocess.py#L720-L721
> 
> At the same time, the method `_result_core_func` has arguments `interp_at_zero` and `Q`, which are never used inside the function code (only the class attribute is used via `self.interp_at_zero`:
> 
> https://github.com/acoular/acoular/blob/d06d58c6f8101ff9ff186905e43802cc19f5b058/acoular/tprocess.py#L913-L1134
> 
> I believe we can delete the method arguments. But what confuses me is that when the method is called in the subclasses `SpatialInterpolatorConstantRotation` and `SpatialInterpolatorRotation`, these unused arguments are given with `interp_at_zero = False`.
> 
> https://github.com/acoular/acoular/blob/d06d58c6f8101ff9ff186905e43802cc19f5b058/acoular/tprocess.py#L1178
> 
> @gherold, could you tell me what the concept was here? Obviously, `interp_at_zero` can also be `True`, and the arguments can be deleted. Is that correct?

@sjekosch may be able to better answer this. I believe the reason for the trait's existence was that due to the interpolation of signals along the azimuthal coordinate you would normally never get a value at the center of the rotation, i.e. the array origin. This parameter would force a value to be calculated there.

I agree, however, that the argument of the same name in the `_result_core_func` appears to be never used (may be an artifact from an earlier implementation) and thus can be removed.
