### ISSUE TITLE
Decide on naming conventions and fix violating methods, arguments, and variable names

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#228]
I would like to discuss some of the following linting errors. 

* The use of ambiguous variable names (Ruff -> E741)
* We have 598 (!) functions, arguments, and variables written in camel case style 
* We have 17 mixed case functions, arguments, and variables
* We use underscores in some class names (primarily but not exclusively in tests)
* Ony may consider renaming the `fastFuncs.py` module, which is also a camel case

**Comment by esarradj** [comment]
I think we can easily fix this where it does not concern the public interface. 
For other cases, e.g. for `L_p`, it would be good to have an overview how severe the problem is.
