### ISSUE TITLE
Better handling of optional packages is needed

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#233]
Some optional functionalities are not handled nicely. This includes:

1. `SoundDeviceSamplesGenerator` and `nidaq_import` classes 

Here, we should get rid of the try and except blocks. One option would be to use the `contextlib.suppress` contextmanager as described here: https://docs.astral.sh/ruff/rules/suppressible-exception/

2. pylops package:

At the moment, if pylops is not installed, there is no message that tells the user that pylops is not available when requested. There should be some way to find out, if pylops is available within Acoular (maybe add support via the `Config`class similar to the `traitsui` feature)

**Comment by esarradj** [comment]
#237 closes this
