### ISSUE TITLE
numpy RandomState.standard_normal needs int input

### ISSUE THREAD

**Issue by andreasfuchs1** [acoular/acoular#24]
Hello, 

I found a bug, which affects newer numpy versions (at least since 14.2 and 15.1):

The method standard_normal from RandomState class needs an integer input, otherwise a TypeError is thrown: TypeError: 'float' object cannot be interpreted as an integer.

https://github.com/acoular/acoular/blob/d207799adc423ba65f1bfe1e829c138cc9ace3d5/acoular/signals.py#L169

A possible fix is:

     s[ind:] += repeat( rnd_gen.standard_normal(int(round(nums / dind+1))), dind)[:lind]

Thanks for your great work on beamforming!

Andreas

**Comment by gherold** [comment]
Hi Andreas,

thanks for pointing this out! The PNoiseGenerator class was due for some updates anyway, but this will accelerate its priority.

Best regards
Gert

**Comment by gherold** [comment]
Issue is resolved now
