### ISSUE TITLE
From wav files to h5

### ISSUE THREAD

**Issue by pierromond** [acoular/acoular#25]
I am wondering how can I pass from a bungh of audio files from the microphones to an h5 file.

Thank you !

Pierre

**Comment by sjekosch** [comment]
Hey Pierre, converting from  .wav to .h5 is possible in Python with the Scipy and Pytables packages. A short Example is given below, it loads the 'audio.wav' as a numpy array and saves it as  'your_filename.h5': 

```
from scipy.io import wavfile
import tables
import numpy

#read data from wav
fs, data = wavfile.read('./folder_to_yout_audio/audio.wav')

#ouput
folder='./output_folder/'
name= 'your_filename.h5'
#save_to acoular h5 format
acoularh5 = tables.open_file(folder+name, mode = "w", title = filename)
acoularh5.create_earray('/','time_data', atom=None, title='', filters=None, \
                         expectedrows=100000, chunkshape=[256,64], \
                         byteorder=None, createparents=False, obj=data)
acoularh5.set_node_attr('/time_data','sample_freq', fs)
acoularh5.close()
```

Cheers, Simon

**Comment by pierromond** [comment]
Dear Simon,

I don't understand why but I still have some issues. I have a numpy array which size is [nsamples, nchanels]. When I use your script and newly open the h5 file, only two channels are detected. Do you have any idea of my mistake ?

Thank you !

Pierre
