### ISSUE TITLE
BUG: `import acoular` fails with `cannot allocate memory in static TLS block` on resource constrained device (Google Coral TPU)

### ISSUE THREAD

**Issue by jake-is-ESD-protected** [acoular/acoular#274]
### Version Dependencies

- Platform: Google Coral TPU dev board
- OS: mendel (debian)
- Python: 3.9.6
- Acoular: 24.5

### Bug Description

`import acoular` fails with

```
ImportError: /home/mendel/.local/lib/python3.9/site-packages/sklearn/utils/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
```

Error originates from `import sklearn`. Issue is referenced [here](https://github.com/opencv/opencv/issues/14884) and [here](https://stackoverflow.com/questions/70446215/torch-lib-libgomp-d22c30c5-so-1-cannot-allocate-memory-in-static-tls-block) but mentions a different platform and target software. Sadly, this keeps me from using `acoular` on an edge device. Can you do anything on your side or is this purely an issue with the platform?

### Reproducible Code

```python
import acoular
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/mendel/Project-AINES/test.py", line 2, in <module>
    from acoular import config, SoundDeviceSamplesGenerator, tools
  File "/home/mendel/.local/lib/python3.9/site-packages/acoular/__init__.py", line 15, in <module>
    from . import demo, tools
  File "/home/mendel/.local/lib/python3.9/site-packages/acoular/tools/__init__.py", line 25, in <module>
    from .metrics import MetricEvaluator
  File "/home/mendel/.local/lib/python3.9/site-packages/acoular/tools/metrics.py", line 23, in <module>
    from acoular.fbeamform import L_p, integrate
  File "/home/mendel/.local/lib/python3.9/site-packages/acoular/fbeamform.py", line 40, in <module>
    import sklearn
  File "/home/mendel/.local/lib/python3.9/site-packages/sklearn/__init__.py", line 97, in <module>
    from .utils._show_versions import show_versions
  File "/home/mendel/.local/lib/python3.9/site-packages/sklearn/utils/_show_versions.py", line 15, in <module>
    from ._openmp_helpers import _openmp_parallelism_enabled
ImportError: /home/mendel/.local/lib/python3.9/site-packages/sklearn/utils/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0: cannot allocate memory in static TLS block
```

### Issue Severity

High: It significantly affects my work, and I cannot find a workaround.

**Comment by esarradj** [comment]
This seems to be unrelated to Acoular, but a problem with the Scikit learn package. Things to try out:
- install sklearn from different source (e.g. via apt instead of pip) 
- remove sklearn dependency from Acoular (only in fbeamform.py), comment out lines 40, 87, 120, 121: CMF, DamasPlus and GIB wont work then, but everything else
- as it is the OpenMP lib that cannot be loaded, maybe you try some LD_PRELOAD tricks as explained in the links you gave

**Comment by jake-is-ESD-protected** [comment]
The problem was actually resolved by setting the `LD_PRELOAD` environment variable:
```bash
export LD_PRELOAD=/home/mendel/.local/lib/python3.9/site-packages/sklearn/utils/../../scikit_learn.libs/libgomp-d22c30c5.so.1.0.0
```
However, this should be saved to `~/.bashrc` to be persistent. Why this is necessary is unknown to me, but that fix works. In any case, whether related or unrelated to this, loading acoular on the mentioned device takes roughly 18 seconds. This only concerns the import, any subsequent functions run at usual speeds for the device.

imho, this issue can be closed after review, thank you.
