### ISSUE TITLE
Deprecated traits used in Acoular's  own code

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#309]
There are multiple instances of traits deprecated in Acoular that are still used in the Acoular code.

This is just one example: [here](https://github.com/acoular/acoular/blame/b61ac4c1e71f47699dadcc9964cdcda5ce8cb168/acoular/grids.py#L600)

Many more are obvious in the output of Acoular unit tests.

**Comment by adku1173** [comment]
With the merge of PR #297, new deprecation warnings are introduced in the tests.
