### ISSUE TITLE
All packages installed but ImportError("packages h5py and pytables are missing!")

### ISSUE THREAD

**Issue by Toktom** [acoular/acoular#35]
Hello, I'm new using Acoular and I'm having some issues with it.
One of them is that yesterday I ran the example "Airfoil in open jet – CMF" and everything went fine, but today I ran the exact same code again and it's giving this weird error, that I quote below.
And I do have all the packages that Acoular require installed, I don't know what is happening.
But the weirdest thing is that when I run the code in Spyder (using Anaconda) it magically works again.
I wish that someone can help me figure it out.
Thanks in advance for your attention.

> Traceback (most recent call last):
>   File "D:\Softwares\Python\lib\site-packages\acoular\configuration.py", line 88, in _assert_h5library
>     import tables
>   File "D:\Softwares\Python\lib\site-packages\tables\__init__.py", line 99, in <module>
>     from .utilsextension import (
>   File "__init__.pxd", line 206, in init tables.utilsextension
>   File "D:\Softwares\Python\lib\site-packages\numpy\__init__.py", line 152, in <module>
>     from . import random
>   File "D:\Softwares\Python\lib\site-packages\numpy\random\__init__.py", line 181, in <module>
>     from . import _pickle
>   File "D:\Softwares\Python\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
>     from .mtrand import RandomState
>   File "_bit_generator.pxd", line 14, in init numpy.random.mtrand
>   File "_bit_generator.pyx", line 255, in init numpy.random._bit_generator
> AttributeError: type object 'numpy.random._bit_generator.SeedSequence' has no attribute '__reduce_cython__'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Softwares\Python\lib\site-packages\acoular\configuration.py", line 92, in _assert_h5library
>     import h5py
>   File "D:\Softwares\Python\lib\site-packages\h5py\__init__.py", line 34, in <module>
>     from . import version
>   File "D:\Softwares\Python\lib\site-packages\h5py\version.py", line 19, in <module>
>     import numpy
>   File "D:\Softwares\Python\lib\site-packages\numpy\__init__.py", line 152, in <module>
>     from . import random
>   File "D:\Softwares\Python\lib\site-packages\numpy\random\__init__.py", line 181, in <module>
>     from . import _pickle
>   File "D:\Softwares\Python\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
>     from .mtrand import RandomState
>   File "_bit_generator.pxd", line 14, in init numpy.random.mtrand
>   File "_bit_generator.pyx", line 255, in init numpy.random._bit_generator
> AttributeError: type object 'numpy.random._bit_generator.SeedSequence' has no attribute '__reduce_cython__'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Workspace\Python\acoular testing\acoular_example_2.py", line 19, in <module>
>     import acoular
>   File "D:\Softwares\Python\lib\site-packages\acoular\__init__.py", line 59, in <module>
>     from .configuration import config
>   File "D:\Softwares\Python\lib\site-packages\acoular\configuration.py", line 99, in <module>
>     config = Config()
>   File "D:\Softwares\Python\lib\site-packages\acoular\configuration.py", line 37, in __init__
>     self._assert_h5library()
>   File "D:\Softwares\Python\lib\site-packages\acoular\configuration.py", line 95, in _assert_h5library
>     raise ImportError("packages h5py and pytables are missing!")
> ImportError: packages h5py and pytables are missing!

**Comment by gherold** [comment]
This looks more like a problem in a different package, maybe due to deprecation. What version of numpy do you have installed?

**Comment by Toktom** [comment]
I have installed the Numpy version 1.18.1.

**Comment by gherold** [comment]
Should be alright, actually. However, the error message still indicates that something with numpy's random number generator's initialization is not working correctly (numpy changed random number handling in 1.17.0). The ImportError thrown does indicate that tables AND h5py could not be imported correctly (because of them not being able to correctly import numpy), so something seems to be really broken in your general python setup.
I'd suggest to install a python distribution with conda, where you can make sure that all dependencies of installed packages are checked automatically.

**Comment by Toktom** [comment]
So I tried to fix it by reinstalling python and all the packages and surprise, didn't work, so I did it again but this time I installed the same version of the packages that I have on my Conda, and also didn't work.
Really weird stuff. So I guess I need to start using Acoular through Conda, where it works.
Thanks anyway.
