### ISSUE TITLE
Beamformer Output

### ISSUE THREAD

**Issue by nanaChang** [acoular/acoular#37]
Hi, 

I'm trying to do Beamforming w/ Acoular. I successfully plotted the rectangular grid out which correctly inferred the potential location of my signal source, but what I'm interested in is to beamform the raw microphone-array signals into single-channel signal and convert into wavfile for higher SNR and better sound quality. I'm wondering if Acoular supports this as well or perhaps it supports only calculating the source location in specific frequency range instead. 

[https://groups.google.com/forum/#!topic/acoular-users/bp5Xd9n8fJQ](url)
My question is extremely similar to this, but I didn't see any useful answer in this discussion either. Therefore I decided to post this out anyway. 

Thank you for reviewing my issue!!

Best, 
Nana Chang

**Comment by nanaChang** [comment]
[A small update]

I've read the documentation of Acoular and dug into the code more these days. I guessed that the beamform in this library supports only locating the source signal and plotting the result on a grid, instead of integrating a multichannel-wavfile into 1 channel. 
However, I'm not sure about my supposition and still looking forward to any further discussion!

Best, 
Nana Chang

**Comment by gherold** [comment]
Extracting filtered time signals in Acoular is possible. You can just feed an BeamformerTime object as source into a WriteWAV object. The grid points you specify are the positions for which you filter and its indices are the "channels" you can select to be exported.
If you want to "integrate" some grid points, keep in mind that with classic beamforming, you will end up with too much energy due to the PSF. (In the upcoming releases we'll see some deconvolution algorithms for time domain beamforming.)
Cheers,
Gert

**Comment by nanaChang** [comment]
Hi @gherold !

Thank you for responding!
I've been playing with writeWAV but I'm still stuck. Can you give me any hint abt how to generate BeamformerTime Object? The only results I can find from any beamformers are in frequency domain or for mapping purpose and I don't think any of those work with writeWAV. 

Thank you again!

Best, 
Nana Chang

**Comment by AmrEzzatIbrahim** [comment]
@nanaChang you can follow this conversation https://groups.google.com/g/acoular-users/c/ZG4BITVNVP4/m/UamY0HwUEAAJ to see how to use BeamformerTime

@gherold is it possible to reconstruct audio signals from the other frequency domain beam-forming outputs of shape (number_freq_bins , num_grid_points) ? 
I followed the BeamformerBase code and I've noticed all frames from the TimeSamples generator are used to calculate the csm and a single map is resulted from all frames. I tried to get a map for each frame and use numpy.fft.irfft to reconstruct the signal in time domain but I end up with just noise.

**Comment by gherold** [comment]
@AmrEzzatIbrahim: No, this won't be possible, as even if you just use a single frame, the beamforming result does not contain any phase info (it's squared sound pressures), so you cannot extract the exact time signal. You would have to implement a frequency-domain beamformer without the CSM. However, at this point, you could just use the BeamformerTime :)

**Comment by AmrEzzatIbrahim** [comment]
Thanks for your fast response. 
Is there a reference for the CSM frequency domain beamforming used in acoular ?

**Comment by gherold** [comment]
I usually recommend this one (covers more than just beamforming with CSM): Sarradj, E. (2012). Three-Dimensional Acoustic Source Mapping with Different Beamforming Steering Vector Formulations. Advances in Acoustics and Vibration, 2012, 1-12.

**Comment by nanaChang** [comment]
@AmrEzzatIbrahim Thank for providing the conversation! I replaced my beamformer with time domain beamforming and succeed generating the wavfile I'm looking for. 
Just to make sure, so the function 'WriteWAV' can only work with time-domain beamformer instead of freq-domain beamformer, that freq-domain beamformer supports no more than mapping the source location with CSM. 
For using time-domain beamformer as source of WriteWAV, setting channel indicates choosing specific grid point from the beamformer. 
CMIIW!

Again, thank you all for these information! It helps a lot!!

Best, 
Nana Chang
