### ISSUE TITLE
Using abc module with traits.api for the definition of abstract base classes

### ISSUE THREAD

**Issue by adku1173** [acoular/acoular#371]
@acoular/acoular-development-team : All Acoular classes are subclassed from the `HasPrivateTraits` class. This issue should discuss: 

1. If the functionality provided by this class is still what we want 
2. If we should use the abc module in conjunction with the traits.api for the definition of abstract base classes

# 1. HasPrivateTraits, HasStrictTraits, or something else?

### Current Implementation

The traits API provides several `HasTraits` subclasses that provide specialized functionality in addition to type checking, caching, and notification handling. Our current approach is to subclass from `HasPrivateTraits`. According to the [documentation](https://docs.enthought.com/traits/traits_api_reference/has_traits.html):

> This class ensures that any public object attribute that does not have an explicit or wildcard trait definition results in an exception, but “private” attributes (whose names start with ‘_’) have an initial value of None, and are not type-checked.

> This feature is useful in cases where a class needs private attributes to keep track of its internal object state, which are not part of the class’s public API. Such attributes do not need to be type-checked, because they are manipulated only by the (presumably correct) methods of the class itself.

To demonstrate it practically, consider the following class

```Python
from traits.api import HasPrivateTraits, Str

class SomePrivateClass(HasPrivateTraits):
    def create_tmp(self):
        self._tmp = 0
```

It is possible to add a private attribute `_tmp` that does not need a trait definition. Therefore, setting the attribute does not involve type-checking. It is even accessible from the outside:

```Python
obj = SomePrivateClass()
obj.create_tmp()
obj._tmp = 10
print(obj._tmp) # prints 10
```

We sometimes make use of this implementation style in Acoular. For example, in the result function of the BeamformerBase class:
https://github.com/acoular/acoular/blob/64ac1ada9c1f83fc2b186695b0f374350a6ced36/acoular/fbeamform.py#L530-L560

Here, the attributes `_ac` and `_fr` are not explicitly defined traits. This would not be possible when using `HasStrictTraits`, which requires an explicit trait definition even for private attributes.

### Possible flaws

Looking at the implementation of `HasPrivateTraits`: 
```Python
class HasPrivateTraits(HasTraits):
    """ This class ensures that any public object attribute that does not have
    an explicit or wildcard trait definition results in an exception, but
    "private" attributes (whose names start with '_') have an initial value of
    **None**, and are not type-checked.

    This feature is useful in cases where a class needs private attributes to
    keep track of its internal object state, which are not part of the class's
    public API. Such attributes do not need to be type-checked, because they
    are manipulated only by the (presumably correct) methods of the class
    itself.
    """

    # Make 'private' traits (leading '_') have no type checking:
    __ = Any(private=True, transient=True)

    # Disallow access to all other traits not explicitly defined:
    _ = Disallow
```

Private attributes are not serializable due to the `transient=True` argument. Thus the following code results in returning `None`

```Python
import pickle
obj._tmp=10
with open('obj.pkl', 'wb') as f:
    pickle.dump(obj, f)

# unpickle the object
with open('obj.pkl', 'rb') as f:
    obj = pickle.load(f)
print(obj._tmp) 
```

I am afraid that this can cause problems when using packages facilitating multi-processing, such as [ray](https://docs.ray.io/en/latest/ray-core/objects/serialization.html), which is utilized by [AcouPipe](https://github.com/adku1173/acoupipe) .Ray uses serialization to transfer objects between processes. So far, I have yet to notice any problems since we rarely use undefined private attributes.  
However, we should think about whether it wouldn't be better to prohibit undefined private attributes and use `HasStrictTraits` as the base class instead. 

# 2. Using ABC module

Traits provide the `ABCHasTraits`, which enables using features from the [abc module](https://docs.python.org/3/library/abc.html). Unfortunately, the traits API only provides the `ABCHasStrictTraits` class per default, but we could simply define an `ABCHasPrivateTraits` class ourselves: 

```Python
class ABCHasPrivateTraits(ABCHasTraits):

    __ = Any(private=True, transient=True)
    _ = Disallow
```
and use this to define abstract base classes in Acoular. The benefit would be:

1. Abstract base classes cannot be instantiated on its own
2. Functions decorated with `@abstractmethod` must be overridden by subclasses (such as the `result` method for generators) 
3. No extra tests for abstract methods

I believe it would make development for people from outside easier.

**Comment by esarradj** [comment]
The only advantage of allowing private traits that are not type-checked that I see is a possibly better performance when these traits are set. I think that this is probably not important in the rare cases we use private traits in Acoular and we can effort to have e.g. `_fr` and `_ac` type-checked, possibly as `Any`. 
If I am right, we could simply replace `HasPrivateTraits` by `HasStrictTraits` and where needed `ABSHasStrictTraits` and define any private traits that have no definition yet.
