### ISSUE TITLE
SineGenerator uses variable called rms as peak amplitude

### ISSUE THREAD

**Issue by ti-sch** [acoular/acoular#38]
Using **acoular** for simulating virtual array data, my results differed from what I would have expected. 

Investigating the code, I quickly realised that the `SineGenerator().rms` trait is used as the peak amplitude of the created signal:
https://github.com/acoular/acoular/blob/d033cb24d672e88f7a349182281f8cda4668fdbc/acoular/signals.py#L203

I was abele to fix it for my code by actually providing the peak amplitude (multiplying by a factor of sqrt(2)). 

If this behaviour isn't intentional (and/or I am missing something) I suggest two possible fixes to prevent confusion for other users:
* Rename the trait to `peak_amplitude`, `p_amp` or something similar, and adding it to the documentation for `SineGenerator`. This might not be feasible, as `rms` is inherited from `SignalGenerator`.
* **better** (IMHO): Add a factor of `sqrt(2)` to the line mentioned above. This way, the value provided by `rms` actually is used as the root mean squared. 

I don't know if the latter breaks any example, but the ones I saw were mostly using the `WNoiseGenerator`. Also, the former would break even more code.

**Comment by gherold** [comment]
This is, indeed, a bug. Thanks for pointing it out!

**Comment by esarradj** [comment]
resolved in v20.10
