### ISSUE TITLE
Beamform

### ISSUE THREAD

**Issue by sagyHarpaz** [acoular/acoular#40]
Hi.
I wonder how can I get output beamforming signal as a one channel wav file.

I have multichannel signal that I want to calculate its beamforming and save the output as single channel wav file.

Please advise.

**Comment by gherold** [comment]
I assume you want to perform beamforming in time domain and then save the result into a wave file.
One possibility would be to define a focus grid with only one point (the one where you expect the signal to be emitted from), define a BeamformerTime object with that grid and use this object as source for a WriteWAV object. 

For support questions, please also consider using our community board: https://groups.google.com/forum/#!forum/acoular-users

**Comment by nnelshas** [comment]
How do you define that point on the grid using the beamforming object in the WriteWAV function?
