### ISSUE TITLE
hardware: sinus apollo typhoon tornado uma16

### ISSUE THREAD

**Issue by hewittzgh** [acoular/acoular#53]
Hello, I'm using spectacoular. I want to use the sinus device you mentioned and uma16. I found that you used several Python packages: sinus and acuma16, but I couldn't find them. You can provide the website of the device, or how can I use these to make full use of spectral for signal processing?
Can I use a self-made microphone array to meet the data input format of spectral? I can transmit and receive data through serial port, USB and network cable.
Thanks!

**Comment by esarradj** [comment]
Yes, it is possible to use UMA16 without problems. The acuma interim package is not needed and you can use `SoundDeviceSamplesGenerator` class for this.
