### ISSUE TITLE
How to feed my data into acoular?

### ISSUE THREAD

**Issue by YoungDev-R** [acoular/acoular#57]
Hi,

What is the simplest way to feed my own data into acoular time series?

I was tinkering with the basic example of 64 microphones and 3 sources and I did not find a way to feed my own data as numpy arrays. So I had to manually create .xml and .h5 files with my own time series and microphone positions. However, I keep having an issue with my h5 file: I get 

AttributeError: Attribute 'sample_freq' does not exist in node: '/time_data'

I use h5py to create my .h5 file and feed my array there. However,h5py does not create an additional attribute, so I can't specify  'sample frequency', and I have been trying to figure out how to feed this sample frequency into the h5 file. I can't seem to do it in h5, does it mean I have to go into the acoular source code to override this? Is there an easier way for me to feed my own data into acoular without having to go through these hoops? I wonder why it isn't anywhere in the tutorials.

Thank you.

**Comment by esarradj** [comment]
This [example](https://gist.github.com/esarradj/7c12c16a6131fc42da11b72042f6e0c9) uses pytables, but you can surely do the thing using h5py.

**Comment by YoungDev-R** [comment]
Thank you for such a fast reply! This helps
