### ISSUE TITLE
New SoundDeviceMaskedSamplesGenerator class?

### ISSUE THREAD

**Issue by qpanpony** [acoular/acoular#61]
class acoular.sdinput.SoundDeviceSamplesGenerator has acoular.tprocess.SamplesGenerator as its base. Do we better have a similar new class acoular.sdinput.SoundDeviceMaskedSamplesGenerator based on acoular.tprocess.MaskedSamplesGenerator? Yes, it is not an issue, but will be more convenient if acoustic array has invalid channels or invalid samples.

**Comment by esarradj** [comment]
Ideally you would mask invalid channels already in the device. Another option is to use `MaskedTimeInOut` as the next processing block after `SoundDeviceSamplesGenerator`. This should give the functionality of a `SoundDeviceMaskedSamplesGenerator`
