### ISSUE TITLE
Wrong line division in LineGrid

### ISSUE THREAD

**Issue by slowglow** [acoular/acoular#66]
The grid points positions returned  by LineGrid are wrong.

For a line along x-axis, from -1.0 m to +1.0 m (i.e. length = 2 m ), when placing 3 points on a grid, I expect to find them at x = -1.0, 0, +1.0. 

Acoular disagrees:
```
>>>lg = acoular.LineGrid(loc=(-1.0, 0, 1), direction=(1.0, 0.0, 0.0), length=2, numpoints=3) 
>>>lg.pos()[0,:]
array([-1.        , -0.33333333,  0.33333333])
```
The length between the end coordinates is only 1.33 m.

**Comment by slowglow** [comment]
It seems this is a case of the [fencepost error](https://en.wikipedia.org/wiki/Off-by-one_error).
A temporary work-around for users is to make the line length a bit longer.
```
deltaS = 1  # spacing between points
Npts = 3
L = Npts*deltaS
lg = acoular.LineGrid(loc=(-1.0, 0, 1), direction=(1.0, 0.0, 0.0), length=L, numpoints=Npts)
lg.pos()[0,:]
```
Returns: 
`array([-1.,  0.,  1.])`

**Comment by sjekosch** [comment]
This issue can be fixed by replacing line 892 in grids.py with:       
 ` dist = self.length / (self.numpoints - 1)`

**Comment by slowglow** [comment]
Thank you for fixing this bug.
