### ISSUE TITLE
Point Spread Function - nMics = distGridToAllMics.shape[0]

### ISSUE THREAD

**Issue by TorosSenan** [acoular/acoular#76]
Dear Acoular team, 

I am trying to understand the point spread function calculations and trying to debug and follow the script by breakpoints, and for that, I extracted the function out of the fastFuncs.py and commented out the gu vectorize section. There I noticed, the nMics variable is wrong: It should be distGridToAllMics.shape[1], since the demo data has 64 microphones, and if the first item is chosen, (since the number of grid points is 1681), the loop exists with an error in the line: expArg = np.float32(waveNumber* (distGridToAllMics[cntMics] - distSourcesToAllMics[cntSources, cntMics])),  since cntMics can't be more than 63. 

When correcting this, the last line of the _psf_Formulation1AkaClassic, expectedly, returns a size mismatch error:  ValueError: could not broadcast input array from shape (64,) into shape (1681,) 

I am curious to know, if somewhere else in the package there is a correction or compensation for this that enables the execution of beamformers that need point spread function calculation.

Best, 

T

**Comment by gherold** [comment]
Hello TorosSenan

This seems somewhat similar to #75 . The gist is, you cannot just comment out the guvectorize section, since it actively changes how the function works and how its arguments are interpreted. The variable `distGridToAllMics` in the function at runtime is 1D and only has as many entries as there are microphones. Hope this helps :)

Cheers 

Gert

**Comment by TorosSenan** [comment]
Dear Gert, 

Thank you for your very quick response. I had a feeling that it was related to the guvectorize function, which is completely a black box for me right now. 

The main reason that I got the point spread function out of the fastfuncs manually is that I could not find a way to debug the function within the acoular using demo data. I tried beamforDAMAS, but, albeit unsure, it seems like it is loading the psf rather than calculating it. Is there a way that I could inspect psf function deeper by using acouar demo data and break-point-by-break-point navigation?

Somehow when I tried using beamformerDAMAS, the code did not stop in the breakpoints within the calPointSpreafFunction. It also does not stop in places that seem relevant (for psf calculation) inside the PointSpreadFunction class within fbeamform.py. Obviously, I am a bit lost.

Thank you in advance, 

Best, 

T

**Comment by gherold** [comment]
Yes, by default the PSF is cached and loaded from disk memory if it has been calculated once for a given setup. Then, you would never enter the routines for calculating it after the initial calculation. You could delete the contents of the associated "cache" folder and/or set the parameter `acoular.config.global_caching = "none"`. I'm actually not sure, however, how  breakpoints behave in parallelized code elements which may even be compiled before running.

**Comment by esarradj** [comment]
T,
it seems like you want to check if the point spread function matches what you would expect. I am not sure if you are aware of the`PointSpreadFunction` class (see [here](http://acoular.org/api_ref/generated/generated/acoular.fbeamform.PointSpreadFunction.html#acoular.fbeamform.PointSpreadFunction) which easily allows to access the PSF directly without any interference with fastfuncs necessary. You set it up by define the steering vector and calc mode and frequency. Then you can access the PSF directly at the `psf` trait. That's it.

**Comment by TorosSenan** [comment]
Hi Gert, 

Thank you. I already figured the psf trait out. I will use that for validation.

Best, 

T

**Comment by TorosSenan** [comment]
Dear Gert and Sarradj,

I have been trying to generate the exact psf output in octave, following up on the paper (Sarradj, 2012) and acoular, but kept failing. It seems like the implementation in fastFuncs does not follow the exact formulae as noted in the paper, or I am unable to connect those. The scalar Product definition under the classical formulation denotes a division of the complex number with one of the distance vectors, but I cant see that in the paper. There is a division with the number of microphones only in Eq. 7.

I could not also trace the normalization factor in the paper, which is defined in the fastFuncs.

The psf results with (1681,1681) sized matrix in the demo data, but the target grid points is (41,41). Am I missing a spatial interpolation parameter maybe? I had the impression that the psf would be the same size with the target grid points if the calc mode is full. 

Sorry for disturbing you with these questions, and thank you for your guidance/help so far.

Best,

t

**Comment by esarradj** [comment]
The PSF is different for each point in the grid. That means we need as many different PSF as we have grid points and each PSF has as many values as we have grid points, So each column (?) holds a full PSF that can be reshaped to (41,41) if you want to plot it. If you want to know which column/row is correspondig to which point, check the Grid class.

**Comment by TorosSenan** [comment]
Thank you for the explanation. I will get into it again with this new clarifications tomorrow. 

I am learning a lot via your work. 

Best,

t

**Comment by TorosSenan** [comment]
Dear Sarradj and Gert, 

After working with the acoular toolbox for the last two days, I came back to the same point that makes me get lost: Why does the function output values differ when the function is vectorized? 

Here I post two plots. First one it the transfer function calculated by the calcTransferFunction in fastFuncs executed via fbeamfom, without me getting involved. The second one is me copy-pasting every line inside the same function to ipython console, and running it. 

The abs(transferFunction) plot of function running inside the acoular workflow: 
![MicrosoftTeams-image](https://github.com/acoular/acoular/assets/91614668/aba80bec-9f3a-4edc-ba3d-8f273f9774c1)

The abs(transferFunction) plot when the code is copy pasted to the ipython console and executed there: 
![MicrosoftTeams-image (1)](https://github.com/acoular/acoular/assets/91614668/46fa736c-6b60-4914-bb29-ed7e0a9a112a)

An when I divide the two, I see this: 
![image](https://github.com/acoular/acoular/assets/91614668/aaa415f0-8ed5-4454-bc52-d72d29c8dce4)

indicating a repeated calculation of the same function. 

Thank you, 

T

**Comment by esarradj** [comment]
I think the key to understand why this is different is to understand how [Numpy ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html) and broadcasting works and how this is generalized by [Numba @guvectorize](https://numba.readthedocs.io/en/stable/user/vectorize.html).
