### ISSUE TITLE
Not building under OS X

### ISSUE THREAD

**Issue by datascienceteam01** [acoular/acoular#8]
Python: Anaconda
Several errors related to gcc:

acoular/beamformer.cpp:3022:36: error: variable length array of non-POD element type 'std::complex<double>'
            std::complex<double> e1[nc];

        ~~~~ ^ ~~~~
181 warnings and 16 errors generated.
error: Command "gcc -fno-strict-aliasing -I/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DMAJOR_VERSION=16 -DMINOR_VERSION=5 -I/anaconda/lib/python2.7/site-packages/scipy/weave -I/anaconda/lib/python2.7/site-packages/scipy/weave/scxx -I/anaconda/lib/python2.7/site-packages/scipy/weave/blitz -I//anaconda/lib/python2.7/site-packages/numpy/core/include -I/anaconda/include/python2.7 -c acoular/beamformer.cpp -o build/temp.macosx-10.6-x86_64-2.7/acoular/beamformer.o -O3 -ffast-math -msse3 -Wno-write-strings" failed with exit status 1

**Comment by esarradj** [comment]
Acoular is currently not supported under OS X. The error is related to scipy.weave which has to be replaced in Acoular anyway.

**Comment by datascienceteam01** [comment]
Is there any known workaround?

**Comment by esarradj** [comment]
Again, Acoular under OS X is not supported and you are completely on your own here.
You may try to create your own OS X version of beamformer.cpp. This can be done by running  acoular/acoular/beamformer_build_openmp.py. Maybe that you don't encounter the compile errors then.
