### ISSUE TITLE
Integrate function of BeamformerBase class does not depend on freq_data.ind_low and freq_data.ind_high

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#83]
Even if only a small frequency range is used in PowerSpectra, integrate is evaluated over full frequency range. In my opinion this is unintuitive for two reasons: 
1. The adjusted frequency range is ignored by the function, which forces the user to manually crop the spectrum to the interesting frequency range afterwards.
2. Some beamforming algorithms may produce maps with zero energy. It is not clear if a (lower/higher) zero frequency-component of the integrated spectrum can be attributed to a missing frequency index or if it is a true result of the method. Thus, one has to prove the given freq_range.  

Proposal: Only integrate over the calculated freq_range (or make it optional settable for backwards compatibility)

**Comment by esarradj** [comment]
Check if initial setting values to NaN leads to problems. If not, initialize result with NaNs.
For backwards compatibility, add config setting that allows user to initialize with zeros instead (however, default should be NaN)

 *By Gert Herold on 2020-04-09T14:39:19 (imported from GitLab)*

**Comment by adku1173** [comment]
With Acoular 24.07 which includes the newly implemented lazy result array, this issue can be closed ([#PR280](https://github.com/acoular/acoular/pull/280)). The arguments `ind_low` and `ind_high` are not required anymore and `integrate` now supports setting the frequency range of interest via `frange` agrument.
