### ISSUE TITLE
Not Py3 compatible

### ISSUE THREAD

**Issue by FlyMyPG** [acoular/acoular#9]
More analysis and scientific packages, especially new packages, are becoming Py3 only.  It would be nice to be able to use acoular with them.

One path forward would be to have 2.7/3.x dual compatibility via the tools at python-future.org.

**Comment by gherold** [comment]
This is actually very high on our to-do list. However, at its current state, acoular needs scipy.weave, which is no longer maintained (and not ported to Python 3). We have several options to replace weave, but none of them is straight-forward, so this'll take a little time.

**Comment by FlyMyPG** [comment]
I'm curious about a Pure-Python approach that could better enable PyPy performance, especially now that PyPy does SIMD optimizations.

Then again, it may be far better to take direct advantage of  the [GPU](http://scottsievert.com/blog/2016/07/01/numpy-gpu/) resources.

I think acoular most needs accelerated hardware support on the Raspberry Pi, perhaps via [QPUlib](https://github.com/mn416/QPULib) or [GPU_FFT](http://www.aholme.co.uk/GPU_FFT/Main.htm).

The RasPi is the ideal core for a DIY interface to Alexa or Google Speech APIs.  Then again, the RasPi does have a microphone array and an FPGA audio beamformer available via the [MATRIX Creator](https://creator.matrix.one/#!/index).

What should acoular include as part of the Py3 transformation?

**Comment by esarradj** [comment]
17.11 is Py3 compatible. Tested: 3.4, 3.5, 3.6
